mentorship/urls.py
from django.urls import path
from .views import *
app_name = "mentorship"

urlpatterns=[
    path('', landing, name='landing'),
    path('field/<int:field_id>/', field, name='field'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns=[
    path('login/',views.loginView,name='login'),
    #logout
    path("logout/",views.logoutView, name="logout"),
    #register
    path("register/",views.register, name="register"),
    #edit profile
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    #view profile
    path('profile/', views.profileView, name='user-profile'),
    #cohort members
    path('cohort/',views.cohort_members, name='cohort_members'),
    #verify members
    path('add_member/<user_id>/', views.verify_member, name= 'add_member'), 
]

weevil/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    #main app 
    path("",include("weevils.urls",namespace="weevils"), ),
    #users app
    path("users/",include("users.urls",namespace= "users"), ),
    path("mentorship/",include("mentorship.urls", namespace="mentorship") ),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weevils/urls.py
from django.urls import path
from . import views

app_name = "weevils"
urlpatterns=[
    path('',views.home,name='home'),
]

mentorship/models.py
from django.db import models
from users.models import Profile

class Field(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="field-images/", blank=True, null=True)
    
    def __str__(self):
        return self.name

class Subfield(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default="This field is about ...")
    field = models.ForeignKey(Field, on_delete=models.CASCADE, related_name="subfields")
    
    def __str__(self):
        return self.name

class Mentor(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    fields = models.ManyToManyField(Subfield , related_name="mentors")
    bio = models.TextField()
    experience = models.TextField()
    availability = models.TextField()
    image = models.ImageField(upload_to="mentor-images/", blank=True, null=True)

    def __str__(self):
        return self.user.user.email
    
class Mentee(models.Model):
    user = models.OneToOneField(Profile, on_delete=models.CASCADE)
    fields = models.ManyToManyField(Field, related_name="mentees")
    bio = models.TextField()
    image = models.ImageField(upload_to="mentee-images/", blank=True, null=True)

    def __str__(self):
        return self.user.user.username

class Mentorship(models.Model):
    mentor = models.ForeignKey(Mentor, on_delete=models.CASCADE)
    mentee = models.ForeignKey(Mentee, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.mentor.user.user.username} - {self.mentee.user.user.username}"

class Message(models.Model):
    mentorship = models.ForeignKey(Mentorship, on_delete=models.CASCADE)
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[:70]


class Testimonial(models.Model):
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    text = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def  __str__(self):
        return self.text[:70]

mentorship/views.py
from django.shortcuts import render
from .models import *

def landing(request):
    fields = Field.objects.all()
    testimonials = Testimonial.objects.all()
    context = {
        'ments': fields,
        'testimonials': testimonials,
               }
    return render(request, 'landing.html',context)

def field(request, field_id):
    field = Field.objects.get(id=field_id)
    context = {
        'field': field,
    }
    return render(request, 'field.html', context)

mentorship/templates/field.html
{% extends 'weevils/base1.html' %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block base %}

    {% include "weevils/navbar.html" %}

            <div class="container-fluid " style="background-image: url({{field.image.url}});background-attachment:fixed; object-fit: cover; font-family:Arial, Helvetica, sans-serif;">
                <div class="display-4 mx-auto text-center pb-2">{{field.name|title}}</div>
                <div class=" d-flex flex-row justify-content-evenly w-100" style="height: 100vh;">
                    
                        {% for sub_field in field.subfields.all %}
                            <div class="">
                                <div class="card  bg-dark border border-primary" style="width: 20rem;">
                                    <div class="card-header display-6">
                                      {{ sub_field }}
                                    </div>
                                    <div class="card-body">
                                      <p class="card-text display-6 pb-2">{{sub_field.description}}</p>
                                    <a class="btn btn-primary" href="#" role="button" data-toggle="modal" data-target="#{{ sub_field.id }}">
                                        See Mentors
                                    </a>
                                    </div>
                                </div>
                                
                                <div class="modal fade text-dark" id="{{ sub_field.id }}" tabindex="-1" role="dialog" aria-labelledby="{{ sub_field.id }}Label" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title " id="{{ sub_field.id }}Label" style=" font-size: 25px;">{{ sub_field }}</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body list-group-flush p-4" style="overflow-y: auto; height: 200px;">
                                                <!-- Add mentor names here -->
                                                {% for mentor in sub_field.mentors.all %}
                                                    <li class="list-group-item">
                                                        <div class="card mb-3" style=" font-size: 18px;">
                                                            <div class="row g-0">
                                                              <div class="col-md-4 py-2 ps-4">
                                                                {% if mentor.image %}
                                                                    <img src="{{ mentor.image.url }}" class="img-fluid rounded-circle" alt="...">
                                                                {% else %}
                                                                    <img src="{% static 'img/dp.png' %}" class="img-fluid rounded-circle" alt="...">
                                                                {% endif %}
                                                              </div>
                                                              <div class="col-md-8">
                                                                <div class="card-body">
                                                                  <h5 class="card-title">{{ mentor }}</h5>
                                                                    <p class="card-text pb-1">{{ mentor.bio|slice:":50" }}...</p>
                                                                  <div class="card-footer w-100" style="background: transparent;">
                                                                    <div class="d-flex flex-row justify-content-between">
                                                                        <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#233a61" d="M64 0C28.7 0 0 28.7 0 64V352c0 35.3 28.7 64 64 64h96v80c0 6.1 3.4 11.6 8.8 14.3s11.9 2.1 16.8-1.5L309.3 416H448c35.3 0 64-28.7 64-64V64c0-35.3-28.7-64-64-64H64z"/></svg>
                                                                    <svg xmlns="http://www.w3.org/2000/svg" height="27" width="27" viewBox="0 0 576 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#253b5f" d="M0 128C0 92.7 28.7 64 64 64H320c35.3 0 64 28.7 64 64V384c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V128zM559.1 99.8c10.4 5.6 16.9 16.4 16.9 28.2V384c0 11.8-6.5 22.6-16.9 28.2s-23 5-32.9-1.6l-96-64L416 337.1V320 192 174.9l14.2-9.5 96-64c9.8-6.5 22.4-7.2 32.9-1.6z"/></svg>
                                                                    <svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#22385e" d="M192 0C139 0 96 43 96 96V256c0 53 43 96 96 96s96-43 96-96V96c0-53-43-96-96-96zM64 216c0-13.3-10.7-24-24-24s-24 10.7-24 24v40c0 89.1 66.2 162.7 152 174.4V464H120c-13.3 0-24 10.7-24 24s10.7 24 24 24h72 72c13.3 0 24-10.7 24-24s-10.7-24-24-24H216V430.4c85.8-11.7 152-85.3 152-174.4V216c0-13.3-10.7-24-24-24s-24 10.7-24 24v40c0 70.7-57.3 128-128 128s-128-57.3-128-128V216z"/></svg>
                                                                    </div>
                                                                  </div>
                                                                </div>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        
                                                    </li>
                                                {% endfor %}
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                        {% endfor %}
                </div>
            </div>
 
{% endblock %}

mentorship/templates/landing.html
{% extends "weevils/base1.html" %}

{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block base %}
<div class="main-wrapper">
    <main>
        <div class="offcanvas offcanvas-start bg-dark text-light" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel" style="font-family: Cambria, Cochin, Georgia, Times, 'Times New Roman', serif;">
            <div class="offcanvas-header">
              <h5 class="offcanvas-title display-4" id="offcanvasExampleLabel">All Fields</h5>
              <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body fs-4">
              <div class="bg-dark text-light">
                <ul class="list-group list-group-flush bg-dark text-light ">
                    {% for ment in ments %}
                    <a href="#" class="list-group-item list-group-item-primary list-group-item-action bg-dark text-light d-flex justify-content-between align-items-start text-break">
                        {{ment.name}}
                    </a>
                    {% endfor %}
                </ul>
              </div>
              <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="offcanvas" aria-label="Close">Back</button>
                <a href="{% url 'weevils:home' %}"><button type="button" class="btn btn-outline-primary">Home</button></a>
              </div>
            </div>
          </div>
        <ul class='slider'>
            {% for ment in ments %}
            <li class='item' style="background-image: url({{ment.image.url}})">
                <div class='content bg-dark text-light rounded p-5'>
                  <h2 class='title'>{{ment.name}}</h2>
                  <p class='description '>
                    <!-- A random testimonial from one of the fields -->
                    Place holder text
                  </p>
                  <a href="{% url 'mentorship:field' ment.id %}"><button type="button">Read More</button></a>
                </div>
              </li>
            {% endfor %}
          </ul>
          <nav class='navy'>
            <ion-icon class='btn prev ' name="arrow-back-outline"> <i class="fa-solid fa-angle-left fa-2xl d-flex align-items-center justify-content-center h-100"></i></ion-icon>
            <ion-icon class='btn next  ' name="arrow-forward-outline"><i class="fa-solid fa-angle-right fa-2xl d-flex align-items-center justify-content-center h-100"></i></ion-icon>
            <a href="{% url 'weevils:home' %}"><div class="btn"><i class="fa-solid fa-house fa-2xl d-flex align-items-center justify-content-center w-100 h-100"></i></div></a>
            <button title="offcanvas" class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                <i class="fa-solid fa-ellipsis"></i>
            </button>
          </nav>
    </main>
</div>
{% endblock %}