users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns=[
    path('login/',views.loginView,name='login'),
    #logout
    path("logout/",views.logoutView, name="logout"),
    #register
    path("register/",views.register, name="register"),
    #edit profile
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    #view profile
    path('profile/', views.profileView, name='user-profile'),
    #cohort members
    path('cohort/',views.cohort_members, name='cohort_members'),
    #verify members
    path('add_member/<user_id>/', views.verify_member, name= 'add_member'), 
]

weevil/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    #main app 
    path("",include("weevils.urls",namespace="weevils"), ),
    #users app
    path("users/",include("users.urls",namespace= "users"), ),
    path("mentorship/",include("mentorship.urls", namespace="mentorship") ),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractUser
)
from PIL import Image
from phonenumber_field.modelfields import PhoneNumberField

#from weevils.models import Cohort 


class UserManager(BaseUserManager):
    #the user manager handles the data stored in the user attributes for each user instance and holds methods for creating new users and superusers
    def create_user(self, name:str, last_name:str , email:str, password:str = None, is_staff=False, is_superuser=False) -> "User":
        """function checks for the required user fields, sets user attributes to their allocated values and creates a normal user"""
        if not email:
            raise ValueError("User must have an email")
        if not name:
            raise ValueError("User must have a first name")
        if not last_name:
            raise ValueError("User must have a last name")
        
        user = self.model(email=self.normalize_email(email))
        user.name = name
        user.last_name = last_name
        user.set_password(password)
        user.is_active = True
        user.is_staff = is_staff
        user.is_superuser = is_superuser

        return user

    def create_superuser(self, name: str, email:str, password:str) -> "User":
        '''contains a function similar to the create_user method but missing the last_name attribute'''
        if not email:
            raise ValueError("User must have an email")
        if not name:
            raise ValueError("User must have a first name")
        
        user = self.model(email=self.normalize_email(email))
        user.name = name
        #user.region = region
        #user.last_name = last_name
        user.set_password(password)
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        '''user = self.create_user(
            name=name,
            last_name= last_name,
            email= email,
            password=password,
            is_staff=True,
            is_superuser=True
        )'''
        user.save()

'''class to specify new user fields'''
class User(AbstractUser):
    #this class is blueprint of each user instance including their attributes that will be stored in the site
    name = models.CharField(verbose_name="Name", max_length=255)
    last_name = models.CharField(verbose_name="Last Name" , max_length=255)
    password = models.CharField(max_length= 255)
    email = models.EmailField(verbose_name="Email", max_length=255, unique=True)
    username = models.CharField(verbose_name="Name", max_length=255)
    #cohort = models.CharField(max_length=250)
    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name']

class Cohort(models.Model):
    cohort_name = models.CharField(max_length=255)
    cohort_president = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True  )



class Profile(models.Model):
    '''Profile model for additional information about users'''
    class VerificationMethod(models.TextChoices):
        COHORTMATES = "cohortmates","cohortmates"
        SOFTCOPY= "softcopy","softcopy"

    class Roles(models.TextChoices):
        MENTOR = "mentor","mentor"
        STUDENT ="student","student"
    
    cohort = models.ForeignKey(Cohort, on_delete=models.CASCADE, null = True )

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)

    verified = models.BooleanField(default= False)
    role = models.CharField(choices=Roles.choices, default=Roles.STUDENT, max_length=50)

    verification_method = models.CharField(choices=VerificationMethod.choices, default=VerificationMethod.COHORTMATES, max_length=50)

    private_profile = models.BooleanField(default=False)

    #user profile pictures
    picture = models.ImageField(default='avatar.png',upload_to='profile/')

    phonenumber = PhoneNumberField(blank=False, help_text="Enter your phone number", default = '+256755565556')

    def __str__(self):
        return f'{self.user.name} '
    
    def save(self, *args, **kwargs):
        # save the profile first
        super().save(*args, **kwargs)

        # resize the image
        img = Image.open(self.picture.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            # create a thumbnail
            img.thumbnail(output_size)
            # overwrite the larger image
            img.save(self.picture.path)

users/forms.py
from typing import Any
from django.forms import ModelForm, FileInput, ImageField
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User,Profile

class UserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email','name','password1','password2']
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''

class ProfileEditForm(ModelForm):
    picture =  ImageField(widget=FileInput)
    verification_method = forms.ChoiceField(choices=Profile.VerificationMethod.choices, widget=forms.Select(attrs={'class':'text-dark','label':'Verification Method'}))
    class  Meta:
        model = Profile
        fields = ['picture','cohort','phonenumber','cohort','verification_method']

class LoginForm(forms.Form):
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from django.http import  Http404

from .models import User,Profile
from .forms import UserCreationForm, ProfileEditForm,LoginForm

def loginView(request):
    #code to login user in using  username and password
    if request.method == "POST": 
        form = LoginForm(data=request.POST)    
        if form.is_valid():
            email = form.cleaned_data['email']    
            password = form.cleaned_data['password']  
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {user.username}")
                return redirect("weevils:home")
            else:
                messages.warning(request, f"login failed")
                return render(request, 'users/login.html', {'form':form})
    else:
        form = LoginForm()
        return render(request, 'users/login.html', {'form':form})

def logoutView(request):
    logout(request)
    return redirect("weevils:home")

def register(request):
    #page to register new users
    if  request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('users:edit_profile')
    else:
        form = UserCreationForm()
    return render(request, 'users/register.html', {'form': form})

def profileView(request):
    profile = request.user.profile
    context = {
        'profile' : profile,
    }
    return  render(request,'users/profile.html',context)


def edit_profile(request):
    #page to edit user profiles
    if request.method == 'POST':
        form = ProfileEditForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            if request.POST['example-radio'] == 'public':
                request.user.profile.private_profile = False
            else:
                request.user.profile.private_profile = True
            form.save()
            
            return redirect("weevils:home")
    else:
        form = ProfileEditForm(instance=request.user.profile)
    return render(request, 'users/edit_profile.html', {'form' : form})

def cohort_members(request):
    cohort = request.user.profile.cohort
    members = User.objects.filter(profile__cohort=cohort).order_by('username')
    context={'members':members}
    #verify cohort member when their verification link is active
    return render(request,'users/cohort_members.html',context)

def verify_member(request,user_id):
    """
    Verify a member of the current logged in user's cohort.
    Redirect back to cohort members page upon success or error.
    """
    try:
        user = User.objects.get(pk=user_id)
    except User.DoesNotExist:
        raise Http404("User does not exist.")
    
    if user != request.user and request.user.profile.cohort == user.profile.cohort:
        user.profile.verified = True
        user.profile.save()
        messages.success(request,"Member has been verified!")
    elif request.user == user:
        messages.error(request,"You cannot verify yourself.")
    else:
        messages.error(request,"You do not have permission to perform this action.")
    return redirect('users:cohort_members')

users/templates/users/cohort_members.html
{% extends 'weevils/base1.html' %}
<!-- html page to show both verified and unverified members -->
{% block base %}

<div class="row">
{% for member in members %}
    {% if member.profile.verified %}
        <div class="col rounded-3 p-4 text-white  border border-secondary">
            <div class="card w-50" style="border-radius: 1rem;">
                <div class="card-header text-dark display-6">
                    {{member.name}}  
                </div>
                <div class="card-body text-dark">
                    Verified member
                </div>
            </div> 
        </div>
    {% else %}
        <div class="col rounded-3 p-4 border border-secondary">
            <div class="card w-50" style="border-radius: 1rem;">
                <div class="card-header text-dark display-6">
                    {{member.name}}  
                </div>
                <div class="card-body">
                    <a href="{% url 'users:add_member' member.id %}">
                        <div class="btn btn-primary">
                            add verification
                        </div>   
                    </a>
                </div>
            </div>
             
            
        </div>
    {% endif %}

{% endfor %}
</div>


{% endblock %}

users/templates/users/edit_profile.html
{% extends "weevils/base1.html" %}

{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block base %}
    <br>
    <div class="home-section container border border-dark p-4 mx-auto text-light" style="border-radius: 10px;" data-background="{% static 'img\Picsart_24-04-20_12-35-00-484.jpg' %}" >
        <div class=" display-5 "><h1>Create your profile</h1></div><br>
        <form  action="{% url 'users:edit_profile' %}" enctype="multipart/form-data" method="POST" >
            {% csrf_token %}
            {% bootstrap_form form layout='vertical' %}
            
            <div class="d-flex flex-row">
              <div>
                <label class="radio-button">
                  <input type="radio" name="example-radio" value="public">
                  <span class="radio"></span>
                  Public Profile
                </label>
                
                <label class="radio-button">
                  <input type="radio" name="example-radio" value="private">
                  <span class="radio"></span>
                  Private Profile
                </label>
              </div>

            </div>
            <button class="auth w-100 rounded-pill" style="font-size: 20px;" type="submit">Save and Request Approval</button>
        </form>
    </div>
{% endblock %}

users/templates/users/login.html
{% extends "weevils/base1.html" %}
{% load static %}
{% load bootstrap5 %}
{% bootstrap_javascript %}
{% bootstrap_css %}
{% block base %}
<section class="vh-90" style="background-color: #000000;">
    <div class="container py-5 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col col-xl-10">
          <div class="card" style="border-radius: 1rem;">
            <div class="row g-0">
              <div class="col-md-6 col-lg-5 d-none d-md-block">
                <img src="{% static 'img/sample.jpg' %}"
                  alt="login form" class="img-fluid w-100 h-100" style="border-radius: 1rem 0 0 1rem;" />
              </div>
              <div class="col-md-6 col-lg-7 d-flex flex-column align-items-center">
                <div class="card-header p-4 w-100 display-5 text-black">
                  <p style="color: rgb(9, 68, 215);">Smackists</p> DUC IN ALTUM
                </div>
                <div class="card-body p-3 p-lg-4 text-black">                      
                  <div role="tabpanel">
                    <ul class="nav nav-tabs font-alt" role="tablist">
                      <li class="active"><a href="#signup" data-toggle="tab"><span class="icon-paperclip"></span>SignUp</a></li>
                      <li><a href="#signin" data-toggle="tab"><span class="icon-lightbulb"></span>Sign in</a></li>
                    </ul>
                    <div class="tab-content">
                      <div class="tab-pane active" id="signup">
                        <div class="row">
                          <div class="btn-grp">
                            <div class="col ">
                              <br>
                              <a href="{% url 'users:register' %}" style="text-decoration: none;">
                                <button class="oauthButton">
                                  <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve"  viewBox="0 0 125 100">
                                    <path d="M60,0 l50,0 a10,10 0 0,1 7,17 l-50,50 a10,10 0 0,1 -13,0 l-50,-50 a10,10 0 0,1 7,-17z" stroke="#000" stroke-width="0" fill="#000" />
                                    <path d="M60,90 l54,0 a10,10 0 0,0 7,-7 l0,-60 -50,50 a15,15 0 0,1 -21,0 l-50,-50 0,60 a10,10 0 0,0 7,7z" stroke="#000" stroke-width="0" fill="#000" />  
                                  </svg>
                                    Continue with Email
                                </button>
                              </a>
                              <br>
                              <button class="oauthButton">
                                        <svg class="icon" viewBox="0 0 24 24">
                                <path d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" fill="#4285F4"></path>
                                <path d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" fill="#34A853"></path>
                                <path d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" fill="#FBBC05"></path>
                                <path d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" fill="#EA4335"></path>
                                <path d="M1 1h22v22H1z" fill="none"></path>
                              </svg>
                                Continue with Google
                              </button>
                            </div>
                          </div>

                        </div>
                      </div>
                      <div class="tab-pane" id="signin">
                        <form action="{% url 'users:login' %}" method="POST">
                          {% csrf_token %}
                          {% bootstrap_form form layout='inline' %}
                          <button class="auth" type="submit">Login</button>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

users/templates/users/profile.html
{% extends "weevils/base1.html" %}

{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block base %}
    <br>
    <div class="container border p-4 mx-auto">
        <div class=" display-5 "><h1>Your profile</h1></div><br>
        {# Display user profile #}
        <h1>{{user.name}}</h1>
        <br>
        <h1>Cohort:</h1>
        <h1>{{user.profile.cohort.cohort_name}}</h1>
    
    </div>
{% endblock %}

users/templates/users/register.html
{% extends "weevils/base1.html" %}
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block base %}

<form action="{% url 'users:register' %}" class="auth home-section " method="POST" data-background="{% static 'img\Picsart_24-04-20_12-35-00-484.jpg' %}">
    <h3>Sign Up Here</h3>
    {% csrf_token %}
    {% bootstrap_form form layout='vertical' %}
    <button class="auth" type="submit">Save and continue</button>
</form>
{% endblock %}