mentorship/urls.py
from django.urls import path
from .views import *
app_name = "mentorship"

urlpatterns=[
    path('', landing, name='landing'),
    path('field/<int:field_id>/', field, name='field'),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns=[
    path('login/',views.loginView,name='login'),
    #logout
    path("logout/",views.logoutView, name="logout"),
    #register
    path("register/",views.register, name="register"),
    #edit profile
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    #view profile
    path('profile/', views.profileView, name='user-profile'),
    #cohort members
    path('cohort/',views.cohort_members, name='cohort_members'),
    #verify members
    path('add_member/<user_id>/', views.verify_member, name= 'add_member'), 
]

weevil/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    #main app 
    path("",include("weevils.urls",namespace="weevils"), ),
    #users app
    path("users/",include("users.urls",namespace= "users"), ),
    path("mentorship/",include("mentorship.urls", namespace="mentorship") ),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

weevils/urls.py
from django.urls import path
from . import views

app_name = "weevils"
urlpatterns=[
    path('',views.home,name='home'),
]

weevils/models.py
from django.db import models
#from users.models import User 

weevils/views.py
from django.shortcuts import render

def  home(request):
    return  render(request, 'weevils/index.html')

weevils/templates/weevils/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
    <link href="{% static 'lib/components-font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    
    <!-- required for the styles to work -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'lib/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link id="color-scheme" href="{% static 'css/colors/default.css' %}" rel="stylesheet">
    <link rel='stylesheet' href='https://static.fontawesome.com/css/fontawesome-app.css'>
<link rel='stylesheet' href='https://pro.fontawesome.com/releases/v5.2.0/css/all.css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel="stylesheet" href="{% static 'css/navbar-style.css' %}">

    
    <title>Weevils</title>
</head>
<body>
    {% if messages %} {% for message in messages %}
    <div style="position: absolute;
        left: 50%; width: 300px;
        border: yellowgreen ;
        background-image: repeating-radial-gradient(  #0c0a0a 80%,#2f312f 90%,#3f4549 90%);
        background-size: 65px 65px;
        z-index: 1002;">
        <div class="alert  text-warning alert-dismissible" role="alert" data-bs-theme="dark">
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button> {{ message }}
        </div>
    </div>
{% endfor %} {% endif %}

    {% block base %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="{% static 'lib/jquery/dist/jquery.js'%}"></script>
    <script src="{% static 'lib/bootstrap/dist/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'lib/wow/dist/wow.js'%}"></script>
    <script src="{% static 'lib/jquery.mb.ytplayer/dist/jquery.mb.YTPlayer.js'%}"></script>
    <script src="{% static 'lib/isotope/dist/isotope.pkgd.js'%}"></script>
    <script src="{% static 'lib/imagesloaded/imagesloaded.pk'%}gd.js"></script>
    <script src="{% static 'lib/flexslider/jquery.flexslider.js'%}"></script>
    <script src="{% static 'lib/owl.carousel/dist/owl.carousel.min.js'%}"></script>
    <script src="{% static 'lib/smoothscroll.js'%}"></script>
    <script src="{% static 'lib/magnific-popup/dist/jquery.magnific-popup.js'%}"></script>
    <script src="{% static 'lib/simple-text-rotator/jquery.simple-text-rotator.min.js'%}"></script>
    <script src="{% static 'js/plugins.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>
    <script src="{% static 'js/script.js'%}"></script>
</body>
</html>

weevils/templates/weevils/index.html
{% extends "weevils/base1.html" %}
{% load static %}

{# Load the tag library #}
{% load bootstrap5 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block base %}


   {% include "weevils/navbar.html" %}

{% if user.is_authenticated %}
<section class="home-section home-parallax home-fade home-full-height bg-dark-30 w-100 h-100" style="background-attachment:fixed; object-fit: cover;" id="home" data-background="{% static 'img/smack3.jpeg' %}">
    
        {% if user.profile.is_seconded or user.is_staff %}

            {# Display a list of available sections of the app in card format, with links to those sections?#}
            <div class="container-fluid p-2">
                <div class="row d-flex flex-row justify-content-evenly w-100">
                    
                     <div class="cardi col-6 col-md-6">
                        
                        <img  src="https://img.icons8.com/3d-fluency/94/roulette.png" alt="roulette"/>
                        <div class="card__label">Trivia</div>
                        
                        <div class="card__content">
                           <p class="card__title">Trivia & Games</p>
                           <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                        </div>
                     </div>
                     <div class="cardi col-6 col-md-6">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#142f5c" d="M112 48a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm40 304V480c0 17.7-14.3 32-32 32s-32-14.3-32-32V256.9L59.4 304.5c-9.1 15.1-28.8 20-43.9 10.9s-20-28.8-10.9-43.9l58.3-97c17.4-28.9 48.6-46.6 82.3-46.6h29.7c33.7 0 64.9 17.7 82.3 46.6l58.3 97c9.1 15.1 4.2 34.8-10.9 43.9s-34.8 4.2-43.9-10.9L232 256.9V480c0 17.7-14.3 32-32 32s-32-14.3-32-32V352H152z"/></svg>
                        <div class="card__label">Mentorship</div>
                        <div class="card__content">
                           <a href="{% url 'mentorship:landing' %}" style="text-decoration: none;">
                              <p class="card__title">Mentorship</p>
                           <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                           </a>
                        </div>
                     </div>
                     <div class="cardi col-6 col-md-6">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#133267" d="M272 384c9.6-31.9 29.5-59.1 49.2-86.2l0 0c5.2-7.1 10.4-14.2 15.4-21.4c19.8-28.5 31.4-63 31.4-100.3C368 78.8 289.2 0 192 0S16 78.8 16 176c0 37.3 11.6 71.9 31.4 100.3c5 7.2 10.2 14.3 15.4 21.4l0 0c19.8 27.1 39.7 54.4 49.2 86.2H272zM192 512c44.2 0 80-35.8 80-80V416H112v16c0 44.2 35.8 80 80 80zM112 176c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-61.9 50.1-112 112-112c8.8 0 16 7.2 16 16s-7.2 16-16 16c-44.2 0-80 35.8-80 80z"/></svg>
                        <div class="card__label">Ideation Hub</div>
                        <div class="card__content">
                           <p class="card__title">Ideation Hub</p>
                           <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                        </div>
                     </div>

                </div>
                <div class="events" style="background-color: transparent;">
                    <div class="options">
                        <div class="option active" style="--optionBackground:url('{% static 'img/events.jpg' %}'); background-repeat: no-repeat;">
                           <div class="shadow"></div>
                           <div class="label">
                              <div class="icon">
                                 <i class="fa-solid fa-music"></i>
                              </div>
                              <div class="info">
                                <div >Cohort</div>
                                <div class="sub">Smack League</div>
                              </div>
                           </div>
                        </div>
                        <div class="option" style="--optionBackground:url('{% static 'img/events1.jpg' %}');">
                           <div class="shadow"></div>
                           <div class="label">
                              <div class="icon">
                                 <i class="fas fa-fire"></i>
                              </div>
                              <div class="info">
                                <div>Cohort</div>
                                <div class="sub">Cook-a-thon</div>
                              </div>
                           </div>
                        </div>
                        <div class="option" style="--optionBackground:url('{% static 'img/events2.jpg' %}');">
                           <div class="shadow"></div>
                           <div class="label">
                              <div class="icon">
                                 <i class="fas fa-car"></i>
                              </div>
                              <div class="info">
                                <div>Cohort</div>
                                <div class="sub">Trophy Tour</div>
                              </div>
                           </div>
                        </div>
                        <div class="option" style="--optionBackground:url('{% static 'img/events4.jpg' %}');">
                           <div class="shadow"></div>
                           <div class="label">
                              <div class="icon">
                                 <i class="fa-solid fa-music"></i>
                              </div>
                              <div class="info">
                                <div>Cohort</div>
                                <div class="sub">Event Name</div>
                              </div>
                           </div>
                        </div>
                        <div class="option" style="--optionBackground:url('{% static 'img/events5.jpg' %}');">
                           <div class="shadow"></div>
                           <div class="label">
                              <div class="icon">
                                 <i class="fas fa-sun"></i>
                              </div>
                              <div class="info">
                                 <div >Cohort</div>
                                 <div class="sub">Event Name</div>
                              </div>
                           </div>
                        </div>
                     </div>
                     
                </div>
               <div class="row d-flex flex-row justify-content-evenly">
                     <div class="cardi col-6 col-md-6">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#273f68" d="M512 240c0 114.9-114.6 208-256 208c-37.1 0-72.3-6.4-104.1-17.9c-11.9 8.7-31.3 20.6-54.3 30.6C73.6 471.1 44.7 480 16 480c-6.5 0-12.3-3.9-14.8-9.9c-2.5-6-1.1-12.8 3.4-17.4l0 0 0 0 0 0 0 0 .3-.3c.3-.3 .7-.7 1.3-1.4c1.1-1.2 2.8-3.1 4.9-5.7c4.1-5 9.6-12.4 15.2-21.6c10-16.6 19.5-38.4 21.4-62.9C17.7 326.8 0 285.1 0 240C0 125.1 114.6 32 256 32s256 93.1 256 208z"/></svg>
                        <div class="card__label">Social Joint</div>
                        <div class="card__content">
                        <p class="card__title">Social Joint</p>
                        <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                        </div>
                     </div>
                     <div class="cardi col-6 col-md-6">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#183972" d="M36.8 192H603.2c20.3 0 36.8-16.5 36.8-36.8c0-7.3-2.2-14.4-6.2-20.4L558.2 21.4C549.3 8 534.4 0 518.3 0H121.7c-16 0-31 8-39.9 21.4L6.2 134.7c-4 6.1-6.2 13.2-6.2 20.4C0 175.5 16.5 192 36.8 192zM64 224V384v80c0 26.5 21.5 48 48 48H336c26.5 0 48-21.5 48-48V384 224H320V384H128V224H64zm448 0V480c0 17.7 14.3 32 32 32s32-14.3 32-32V224H512z"/></svg>
                        <div class="card__label">Virtual Store</div>
                        <div class="card__content">
                        <p class="card__title">Virtual Stores</p>
                        <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                        </div>
                     </div>
                     <div class="cardi col-6 col-md-6">
                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--!Font Awesome Free 6.5.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#152f5b" d="M160 80c0-26.5 21.5-48 48-48h32c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H208c-26.5 0-48-21.5-48-48V80zM0 272c0-26.5 21.5-48 48-48H80c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V272zM368 96h32c26.5 0 48 21.5 48 48V432c0 26.5-21.5 48-48 48H368c-26.5 0-48-21.5-48-48V144c0-26.5 21.5-48 48-48z"/></svg>
                        <div class="card__label">Weevil Grid</div>
                        <div class="card__content">
                        <p class="card__title">Weevil Grid</p>
                        <p class="card__description">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
                        </div>
                     </div>
                   
                   
               </div>
            </div>
            
        {% endif %}
    
   
   </section>
   {% else %}
   {% include 'weevils/nothing-page.html' %}
   {% endif %}
{% endblock %}

   
     
    

weevils/templates/weevils/navbar.html
<header class="site-navbar " role="banner" style="height: 70px;">
    <nav class="navbar navbar-custom navbar-fixed-top navbar-transparent" role="navigation">
        <div class="container">
          
            <ul class="nav navbar-nav navbar-right d-flex flex-row">
              <li><a class="navbar-brand" href="{% url 'weevils:home' %}">Weevil</a></li>
                <li><a href="{% url 'weevils:home' %}">Home</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'users:user-profile' %}">Profile</a></li>
                <li><a href="{% url 'users:logout' %}">Logout</a></li>
                {% if user.is_staff %}
                    <li><a href="{% url 'users:cohort_members' %}">Cohort</a></li>
                {% endif %}
                {% else %}
                <li><a href="{% url 'users:login' %}">Login</a></li>
                <li><a href="{% url 'users:register' %}">Register</a></li>
                {% endif %}
              
            </ul>
        </div>
      </nav>
</header>

weevils/templates/weevils/nothing-page.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Google tag (gtag.js) -->
    <script
      async
      src="https://www.googletagmanager.com/gtag/js?id=G-1752YPLP7H"
    ></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag() {
        dataLayer.push(arguments);
      }
      gtag("js", new Date());

      gtag("config", "G-1752YPLP7H");
    </script>
    <link rel="stylesheet" href="{% static 'css/404.css' %}">
  </head>

  <body class="permission_denied">
    <div id="tsparticles"></div>
    <div class="denied__wrapper">
      {% if user.is_authenticated == 'False' %}
      <h2 class="display-6">Your account is pending <center>verification.</center></h2>
      {% else %}
      <h2 class="display-6">You are not logged in</h2>
      {% endif %}
      
      <img id="astronaut" src="{% static 'img/astronaut.svg' %}" alt="pictures" />
      <img id="planet" src="{% static 'img/planet.svg' %}" alt="pictures" />
      <a href="{% url 'users:login' %}"><button class="denied__link">Login</button></a>
    </div>

    <script
      type="text/javascript"
      src="https://cdn.jsdelivr.net/npm/tsparticles@2/tsparticles.bundle.min.js"
    ></script>
    <script type="text/javascript" src="{% static 'js/404.js' %}"></script>
  </body>
</html>